// Regenerates docs/api.md from the live Fastify route tree. No DB needed
// (buildApp does not connect). Run: tsx scripts/gen-api-docs.ts
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildApp } from '../apps/api/src/app';

async function main(): Promise<void> {
  process.env.NODE_ENV = 'test'; // quiet logger
  const app = await buildApp();
  await app.ready();
  const tree = app.printRoutes({ commonPrefix: false });
  const out = `# API route inventory\n\nAuto-generated by \`scripts/gen-api-docs.ts\` from the Fastify route tree.\n\n\`\`\`\n${tree}\`\`\`\n`;
  writeFileSync(join(__dirname, '..', 'docs', 'api.md'), out);
  await app.close();
  console.log('Wrote docs/api.md');
}

void main();
