// PDF service. Renders HTML templates to PDF via puppeteer-core when a Chromium
// executable is available (PUPPETEER_EXECUTABLE_PATH / CHROME_PATH); otherwise
// writes the HTML artifact (still a valid, inspectable deliverable).
import { mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

const layout = (title: string, body: string): string => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#0f172a;margin:0;padding:48px;line-height:1.5}
  .brand{font-weight:700;letter-spacing:-.02em;color:#0f172a} .muted{color:#64748b}
  h1{font-size:30px;margin:0 0 8px} h2{font-size:18px;margin:28px 0 8px;border-bottom:1px solid #e2e8f0;padding-bottom:6px}
  .card{border:1px solid #e2e8f0;border-radius:14px;padding:28px;margin-top:20px}
  table{width:100%;border-collapse:collapse;margin-top:8px} td,th{text-align:left;padding:8px 6px;border-bottom:1px solid #eef2f7;font-size:14px}
  .big{font-size:44px;font-weight:800;letter-spacing:-.03em} .seal{display:inline-block;padding:6px 12px;border-radius:999px;background:#eef2ff;color:#4338ca;font-weight:600;font-size:13px}
</style></head><body>
<div class="brand">out-of-house.dev</div>
${body}
<p class="muted" style="margin-top:48px;font-size:12px">Generated by out-of-house.dev · ${esc(title)}</p>
</body></html>`;

const esc = (s: unknown): string => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export type TemplateName = 'certificate' | 'monthly-report' | 'aiseo-report' | 'quote-sow';

export const TEMPLATES: Record<TemplateName, (d: Record<string, unknown>) => string> = {
  certificate: (d) =>
    layout(
      'Certificate of completion',
      `<div class="card" style="text-align:center">
        <span class="seal">Verified credential</span>
        <h1 style="margin-top:18px">Certificate of Completion</h1>
        <p class="muted">This certifies that</p>
        <div class="big">${esc(d.recipient_name)}</div>
        <p>has successfully completed <strong>${esc(d.programme_name)}</strong>${d.grade ? ` with grade <strong>${esc(d.grade)}</strong>` : ''}.</p>
        <p class="muted">Issued ${esc(d.issued_at)} · Code <strong>${esc(d.certificate_code)}</strong></p>
        <p class="muted" style="font-size:12px">Verify at ${esc(d.verification_url)}</p>
      </div>`,
    ),
  'monthly-report': (d) =>
    layout(
      'Monthly impact report',
      `<h1>Monthly impact — ${esc(d.project_name)}</h1>
       <p class="muted">${esc(d.period_start)} → ${esc(d.period_end)}</p>
       <div class="card">
         <h2>Highlights</h2>
         <table><tr><th>Shipped</th><td>${esc(d.shipped ?? 0)}</td></tr>
         <tr><th>Uptime</th><td>${esc(d.uptime ?? '—')}</td></tr>
         <tr><th>Hours saved (est.)</th><td>${esc(d.hours_saved ?? '—')}</td></tr></table>
       </div>
       <div class="card"><h2>Narrative</h2><p>${esc(d.narrative ?? 'A steady month of delivery.')}</p></div>`,
    ),
  'aiseo-report': (d) =>
    layout(
      'AISEO report',
      `<h1>AISEO report — ${esc(d.domain)}</h1>
       <p>Audit grade <strong>${esc(d.grade)}</strong> (score ${esc(d.score)}/100).</p>
       <div class="card"><h2>Engine presence</h2>
         <table><tr><th>Engine</th><th>Present</th><th>Position</th></tr>
         ${((d.rankings as Array<Record<string, unknown>>) ?? []).map((r) => `<tr><td>${esc(r.engine)}</td><td>${r.brand_present ? 'Yes' : 'No'}</td><td>${esc(r.rank_position ?? '—')}</td></tr>`).join('')}
         </table>
       </div>
       <div class="card"><h2>Summary</h2><p>${esc(d.summary ?? '')}</p></div>`,
    ),
  'quote-sow': (d) =>
    layout(
      'Quote + statement of work',
      `<h1>Quote — ${esc(d.title)}</h1>
       <div class="card"><h2>Line items</h2>
         <table><tr><th>Item</th><th style="text-align:right">Price</th></tr>
         ${((d.line_items as Array<Record<string, unknown>>) ?? []).map((li) => `<tr><td>${esc(li.name)}</td><td style="text-align:right">£${esc(Math.round(Number(li.pence ?? 0) / 100))}</td></tr>`).join('')}
         <tr><th>Total</th><th style="text-align:right">£${esc(Math.round(Number(d.total_pence ?? 0) / 100))}</th></tr></table>
       </div>
       <div class="card"><h2>Statement of work</h2><p>${esc(d.sow_md ?? '')}</p>
       <p class="muted">Deposit ${esc(d.deposit_pct ?? 50)}% on acceptance.</p></div>`,
    ),
};

export async function renderPdf(template: TemplateName, data: Record<string, unknown>, outPath: string): Promise<{ path: string; format: 'pdf' | 'html'; bytes: number }> {
  const html = TEMPLATES[template](data);
  mkdirSync(dirname(outPath), { recursive: true });
  const execPath = process.env.PUPPETEER_EXECUTABLE_PATH || process.env.CHROME_PATH;
  if (execPath) {
    try {
      const spec = 'puppeteer-core';
      const puppeteer = (await import(spec)) as unknown as {
        launch: (o: Record<string, unknown>) => Promise<{ newPage: () => Promise<{ setContent: (h: string, o: Record<string, unknown>) => Promise<void>; pdf: (o: Record<string, unknown>) => Promise<void> }>; close: () => Promise<void> }>;
      };
      const browser = await puppeteer.launch({ executablePath: execPath, headless: true, args: ['--no-sandbox'] });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });
      await page.pdf({ path: outPath, format: 'A4', printBackground: true });
      await browser.close();
      return { path: outPath, format: 'pdf', bytes: statSync(outPath).size };
    } catch {
      /* fall through to HTML */
    }
  }
  const htmlPath = outPath.replace(/\.pdf$/i, '.html');
  writeFileSync(htmlPath, html);
  return { path: htmlPath, format: 'html', bytes: Buffer.byteLength(html) };
}
